// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/java/top/meethigher/proxy/tcp/tunnel/proto/origin/tunnelMessage.proto
// Protobuf Java Version: 4.30.2

package top.meethigher.proxy.tcp.tunnel.proto;

public final class TunnelMessage {
  private TunnelMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface AuthOrBuilder extends
      // @@protoc_insertion_point(interface_extends:top.meethigher.proxy.tcp.tunnel.proto.Auth)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string token = 1;</code>
     * @return The token.
     */
    java.lang.String getToken();
    /**
     * <code>string token = 1;</code>
     * @return The bytes for token.
     */
    com.google.protobuf.ByteString
        getTokenBytes();
  }
  /**
   * Protobuf type {@code top.meethigher.proxy.tcp.tunnel.proto.Auth}
   */
  public  static final class Auth extends
      com.google.protobuf.GeneratedMessageLite<
          Auth, Auth.Builder> implements
      // @@protoc_insertion_point(message_implements:top.meethigher.proxy.tcp.tunnel.proto.Auth)
      AuthOrBuilder {
    private Auth() {
      token_ = "";
    }
    public static final int TOKEN_FIELD_NUMBER = 1;
    private java.lang.String token_;
    /**
     * <code>string token = 1;</code>
     * @return The token.
     */
    @java.lang.Override
    public java.lang.String getToken() {
      return token_;
    }
    /**
     * <code>string token = 1;</code>
     * @return The bytes for token.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getTokenBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(token_);
    }
    /**
     * <code>string token = 1;</code>
     * @param value The token to set.
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void setToken(
        java.lang.String value) {
      value.getClass();  // minimal bytecode null check

      token_ = value;
    }
    /**
     * <code>string token = 1;</code>
     */
    private void clearToken() {

      token_ = getDefaultInstance().getToken();
    }
    /**
     * <code>string token = 1;</code>
     * @param value The bytes for token to set.
     */
    private void setTokenBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      token_ = value.toStringUtf8();

    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Auth parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Auth parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Auth parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Auth parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Auth parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Auth parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Auth parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Auth parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Auth parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Auth parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Auth parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Auth parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Auth prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code top.meethigher.proxy.tcp.tunnel.proto.Auth}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Auth, Builder> implements
        // @@protoc_insertion_point(builder_implements:top.meethigher.proxy.tcp.tunnel.proto.Auth)
        top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.AuthOrBuilder {
      // Construct using top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Auth.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string token = 1;</code>
       * @return The token.
       */
      @java.lang.Override
      public java.lang.String getToken() {
        return instance.getToken();
      }
      /**
       * <code>string token = 1;</code>
       * @return The bytes for token.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getTokenBytes() {
        return instance.getTokenBytes();
      }
      /**
       * <code>string token = 1;</code>
       * @param value The token to set.
       * @return This builder for chaining.
       */
      public Builder setToken(
          java.lang.String value) {
        copyOnWrite();
        instance.setToken(value);
        return this;
      }
      /**
       * <code>string token = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearToken() {
        copyOnWrite();
        instance.clearToken();
        return this;
      }
      /**
       * <code>string token = 1;</code>
       * @param value The bytes for token to set.
       * @return This builder for chaining.
       */
      public Builder setTokenBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setTokenBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:top.meethigher.proxy.tcp.tunnel.proto.Auth)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Auth();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "token_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Auth> parser = PARSER;
          if (parser == null) {
            synchronized (top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Auth.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Auth>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:top.meethigher.proxy.tcp.tunnel.proto.Auth)
    private static final top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Auth DEFAULT_INSTANCE;
    static {
      Auth defaultInstance = new Auth();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Auth.class, defaultInstance);
    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Auth getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Auth> PARSER;

    public static com.google.protobuf.Parser<Auth> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface AuthAckOrBuilder extends
      // @@protoc_insertion_point(interface_extends:top.meethigher.proxy.tcp.tunnel.proto.AuthAck)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    boolean getSuccess();

    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code top.meethigher.proxy.tcp.tunnel.proto.AuthAck}
   */
  public  static final class AuthAck extends
      com.google.protobuf.GeneratedMessageLite<
          AuthAck, AuthAck.Builder> implements
      // @@protoc_insertion_point(message_implements:top.meethigher.proxy.tcp.tunnel.proto.AuthAck)
      AuthAckOrBuilder {
    private AuthAck() {
      message_ = "";
    }
    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_;
    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }
    /**
     * <code>bool success = 1;</code>
     * @param value The success to set.
     */
    private void setSuccess(boolean value) {
      
      success_ = value;
    }
    /**
     * <code>bool success = 1;</code>
     */
    private void clearSuccess() {

      success_ = false;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private java.lang.String message_;
    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      return message_;
    }
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(message_);
    }
    /**
     * <code>string message = 2;</code>
     * @param value The message to set.
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void setMessage(
        java.lang.String value) {
      value.getClass();  // minimal bytecode null check

      message_ = value;
    }
    /**
     * <code>string message = 2;</code>
     */
    private void clearMessage() {

      message_ = getDefaultInstance().getMessage();
    }
    /**
     * <code>string message = 2;</code>
     * @param value The bytes for message to set.
     */
    private void setMessageBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      message_ = value.toStringUtf8();

    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.AuthAck parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.AuthAck parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.AuthAck parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.AuthAck parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.AuthAck parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.AuthAck parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.AuthAck parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.AuthAck parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.AuthAck parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.AuthAck parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.AuthAck parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.AuthAck parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.AuthAck prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code top.meethigher.proxy.tcp.tunnel.proto.AuthAck}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.AuthAck, Builder> implements
        // @@protoc_insertion_point(builder_implements:top.meethigher.proxy.tcp.tunnel.proto.AuthAck)
        top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.AuthAckOrBuilder {
      // Construct using top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.AuthAck.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>bool success = 1;</code>
       * @return The success.
       */
      @java.lang.Override
      public boolean getSuccess() {
        return instance.getSuccess();
      }
      /**
       * <code>bool success = 1;</code>
       * @param value The success to set.
       * @return This builder for chaining.
       */
      public Builder setSuccess(boolean value) {
        copyOnWrite();
        instance.setSuccess(value);
        return this;
      }
      /**
       * <code>bool success = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSuccess() {
        copyOnWrite();
        instance.clearSuccess();
        return this;
      }

      /**
       * <code>string message = 2;</code>
       * @return The message.
       */
      @java.lang.Override
      public java.lang.String getMessage() {
        return instance.getMessage();
      }
      /**
       * <code>string message = 2;</code>
       * @return The bytes for message.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getMessageBytes() {
        return instance.getMessageBytes();
      }
      /**
       * <code>string message = 2;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        copyOnWrite();
        instance.setMessage(value);
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        copyOnWrite();
        instance.clearMessage();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMessageBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:top.meethigher.proxy.tcp.tunnel.proto.AuthAck)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.AuthAck();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "success_",
              "message_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0007\u0002\u0208" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.AuthAck> parser = PARSER;
          if (parser == null) {
            synchronized (top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.AuthAck.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.AuthAck>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:top.meethigher.proxy.tcp.tunnel.proto.AuthAck)
    private static final top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.AuthAck DEFAULT_INSTANCE;
    static {
      AuthAck defaultInstance = new AuthAck();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        AuthAck.class, defaultInstance);
    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.AuthAck getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<AuthAck> PARSER;

    public static com.google.protobuf.Parser<AuthAck> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface HeartbeatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:top.meethigher.proxy.tcp.tunnel.proto.Heartbeat)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int64 timestamp = 1;</code>
     * @return The timestamp.
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code top.meethigher.proxy.tcp.tunnel.proto.Heartbeat}
   */
  public  static final class Heartbeat extends
      com.google.protobuf.GeneratedMessageLite<
          Heartbeat, Heartbeat.Builder> implements
      // @@protoc_insertion_point(message_implements:top.meethigher.proxy.tcp.tunnel.proto.Heartbeat)
      HeartbeatOrBuilder {
    private Heartbeat() {
    }
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timestamp_;
    /**
     * <code>int64 timestamp = 1;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>int64 timestamp = 1;</code>
     * @param value The timestamp to set.
     */
    private void setTimestamp(long value) {
      
      timestamp_ = value;
    }
    /**
     * <code>int64 timestamp = 1;</code>
     */
    private void clearTimestamp() {

      timestamp_ = 0L;
    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Heartbeat parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Heartbeat parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Heartbeat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Heartbeat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Heartbeat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Heartbeat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Heartbeat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Heartbeat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Heartbeat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Heartbeat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Heartbeat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Heartbeat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Heartbeat prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code top.meethigher.proxy.tcp.tunnel.proto.Heartbeat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Heartbeat, Builder> implements
        // @@protoc_insertion_point(builder_implements:top.meethigher.proxy.tcp.tunnel.proto.Heartbeat)
        top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.HeartbeatOrBuilder {
      // Construct using top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Heartbeat.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int64 timestamp = 1;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return instance.getTimestamp();
      }
      /**
       * <code>int64 timestamp = 1;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        copyOnWrite();
        instance.setTimestamp(value);
        return this;
      }
      /**
       * <code>int64 timestamp = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        copyOnWrite();
        instance.clearTimestamp();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:top.meethigher.proxy.tcp.tunnel.proto.Heartbeat)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Heartbeat();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "timestamp_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0002";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Heartbeat> parser = PARSER;
          if (parser == null) {
            synchronized (top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Heartbeat.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Heartbeat>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:top.meethigher.proxy.tcp.tunnel.proto.Heartbeat)
    private static final top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Heartbeat DEFAULT_INSTANCE;
    static {
      Heartbeat defaultInstance = new Heartbeat();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Heartbeat.class, defaultInstance);
    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Heartbeat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Heartbeat> PARSER;

    public static com.google.protobuf.Parser<Heartbeat> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface HeartbeatAckOrBuilder extends
      // @@protoc_insertion_point(interface_extends:top.meethigher.proxy.tcp.tunnel.proto.HeartbeatAck)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int64 timestamp = 1;</code>
     * @return The timestamp.
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code top.meethigher.proxy.tcp.tunnel.proto.HeartbeatAck}
   */
  public  static final class HeartbeatAck extends
      com.google.protobuf.GeneratedMessageLite<
          HeartbeatAck, HeartbeatAck.Builder> implements
      // @@protoc_insertion_point(message_implements:top.meethigher.proxy.tcp.tunnel.proto.HeartbeatAck)
      HeartbeatAckOrBuilder {
    private HeartbeatAck() {
    }
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timestamp_;
    /**
     * <code>int64 timestamp = 1;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>int64 timestamp = 1;</code>
     * @param value The timestamp to set.
     */
    private void setTimestamp(long value) {
      
      timestamp_ = value;
    }
    /**
     * <code>int64 timestamp = 1;</code>
     */
    private void clearTimestamp() {

      timestamp_ = 0L;
    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.HeartbeatAck parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.HeartbeatAck parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.HeartbeatAck parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.HeartbeatAck parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.HeartbeatAck parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.HeartbeatAck parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.HeartbeatAck parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.HeartbeatAck parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.HeartbeatAck parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.HeartbeatAck parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.HeartbeatAck parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.HeartbeatAck parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.HeartbeatAck prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code top.meethigher.proxy.tcp.tunnel.proto.HeartbeatAck}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.HeartbeatAck, Builder> implements
        // @@protoc_insertion_point(builder_implements:top.meethigher.proxy.tcp.tunnel.proto.HeartbeatAck)
        top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.HeartbeatAckOrBuilder {
      // Construct using top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.HeartbeatAck.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int64 timestamp = 1;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return instance.getTimestamp();
      }
      /**
       * <code>int64 timestamp = 1;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        copyOnWrite();
        instance.setTimestamp(value);
        return this;
      }
      /**
       * <code>int64 timestamp = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        copyOnWrite();
        instance.clearTimestamp();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:top.meethigher.proxy.tcp.tunnel.proto.HeartbeatAck)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.HeartbeatAck();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "timestamp_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0002";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.HeartbeatAck> parser = PARSER;
          if (parser == null) {
            synchronized (top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.HeartbeatAck.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.HeartbeatAck>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:top.meethigher.proxy.tcp.tunnel.proto.HeartbeatAck)
    private static final top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.HeartbeatAck DEFAULT_INSTANCE;
    static {
      HeartbeatAck defaultInstance = new HeartbeatAck();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        HeartbeatAck.class, defaultInstance);
    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.HeartbeatAck getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<HeartbeatAck> PARSER;

    public static com.google.protobuf.Parser<HeartbeatAck> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface OpenPortOrBuilder extends
      // @@protoc_insertion_point(interface_extends:top.meethigher.proxy.tcp.tunnel.proto.OpenPort)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int32 port = 2222;</code>
     * @return The port.
     */
    int getPort();
  }
  /**
   * Protobuf type {@code top.meethigher.proxy.tcp.tunnel.proto.OpenPort}
   */
  public  static final class OpenPort extends
      com.google.protobuf.GeneratedMessageLite<
          OpenPort, OpenPort.Builder> implements
      // @@protoc_insertion_point(message_implements:top.meethigher.proxy.tcp.tunnel.proto.OpenPort)
      OpenPortOrBuilder {
    private OpenPort() {
    }
    public static final int PORT_FIELD_NUMBER = 2222;
    private int port_;
    /**
     * <code>int32 port = 2222;</code>
     * @return The port.
     */
    @java.lang.Override
    public int getPort() {
      return port_;
    }
    /**
     * <code>int32 port = 2222;</code>
     * @param value The port to set.
     */
    private void setPort(int value) {
      
      port_ = value;
    }
    /**
     * <code>int32 port = 2222;</code>
     */
    private void clearPort() {

      port_ = 0;
    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenPort parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenPort parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenPort parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenPort parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenPort parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenPort parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenPort parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenPort parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenPort parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenPort parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenPort parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenPort parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenPort prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code top.meethigher.proxy.tcp.tunnel.proto.OpenPort}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenPort, Builder> implements
        // @@protoc_insertion_point(builder_implements:top.meethigher.proxy.tcp.tunnel.proto.OpenPort)
        top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenPortOrBuilder {
      // Construct using top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenPort.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int32 port = 2222;</code>
       * @return The port.
       */
      @java.lang.Override
      public int getPort() {
        return instance.getPort();
      }
      /**
       * <code>int32 port = 2222;</code>
       * @param value The port to set.
       * @return This builder for chaining.
       */
      public Builder setPort(int value) {
        copyOnWrite();
        instance.setPort(value);
        return this;
      }
      /**
       * <code>int32 port = 2222;</code>
       * @return This builder for chaining.
       */
      public Builder clearPort() {
        copyOnWrite();
        instance.clearPort();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:top.meethigher.proxy.tcp.tunnel.proto.OpenPort)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenPort();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "port_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u08ae\u08ae\u0001\u0000\u0000\u0000\u08ae\u0004";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenPort> parser = PARSER;
          if (parser == null) {
            synchronized (top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenPort.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenPort>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:top.meethigher.proxy.tcp.tunnel.proto.OpenPort)
    private static final top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenPort DEFAULT_INSTANCE;
    static {
      OpenPort defaultInstance = new OpenPort();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        OpenPort.class, defaultInstance);
    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenPort getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<OpenPort> PARSER;

    public static com.google.protobuf.Parser<OpenPort> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface OpenPortAckOrBuilder extends
      // @@protoc_insertion_point(interface_extends:top.meethigher.proxy.tcp.tunnel.proto.OpenPortAck)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    boolean getSuccess();

    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code top.meethigher.proxy.tcp.tunnel.proto.OpenPortAck}
   */
  public  static final class OpenPortAck extends
      com.google.protobuf.GeneratedMessageLite<
          OpenPortAck, OpenPortAck.Builder> implements
      // @@protoc_insertion_point(message_implements:top.meethigher.proxy.tcp.tunnel.proto.OpenPortAck)
      OpenPortAckOrBuilder {
    private OpenPortAck() {
      message_ = "";
    }
    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_;
    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }
    /**
     * <code>bool success = 1;</code>
     * @param value The success to set.
     */
    private void setSuccess(boolean value) {
      
      success_ = value;
    }
    /**
     * <code>bool success = 1;</code>
     */
    private void clearSuccess() {

      success_ = false;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private java.lang.String message_;
    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      return message_;
    }
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(message_);
    }
    /**
     * <code>string message = 2;</code>
     * @param value The message to set.
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void setMessage(
        java.lang.String value) {
      value.getClass();  // minimal bytecode null check

      message_ = value;
    }
    /**
     * <code>string message = 2;</code>
     */
    private void clearMessage() {

      message_ = getDefaultInstance().getMessage();
    }
    /**
     * <code>string message = 2;</code>
     * @param value The bytes for message to set.
     */
    private void setMessageBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      message_ = value.toStringUtf8();

    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenPortAck parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenPortAck parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenPortAck parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenPortAck parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenPortAck parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenPortAck parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenPortAck parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenPortAck parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenPortAck parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenPortAck parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenPortAck parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenPortAck parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenPortAck prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code top.meethigher.proxy.tcp.tunnel.proto.OpenPortAck}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenPortAck, Builder> implements
        // @@protoc_insertion_point(builder_implements:top.meethigher.proxy.tcp.tunnel.proto.OpenPortAck)
        top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenPortAckOrBuilder {
      // Construct using top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenPortAck.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>bool success = 1;</code>
       * @return The success.
       */
      @java.lang.Override
      public boolean getSuccess() {
        return instance.getSuccess();
      }
      /**
       * <code>bool success = 1;</code>
       * @param value The success to set.
       * @return This builder for chaining.
       */
      public Builder setSuccess(boolean value) {
        copyOnWrite();
        instance.setSuccess(value);
        return this;
      }
      /**
       * <code>bool success = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSuccess() {
        copyOnWrite();
        instance.clearSuccess();
        return this;
      }

      /**
       * <code>string message = 2;</code>
       * @return The message.
       */
      @java.lang.Override
      public java.lang.String getMessage() {
        return instance.getMessage();
      }
      /**
       * <code>string message = 2;</code>
       * @return The bytes for message.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getMessageBytes() {
        return instance.getMessageBytes();
      }
      /**
       * <code>string message = 2;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        copyOnWrite();
        instance.setMessage(value);
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        copyOnWrite();
        instance.clearMessage();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMessageBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:top.meethigher.proxy.tcp.tunnel.proto.OpenPortAck)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenPortAck();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "success_",
              "message_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0007\u0002\u0208" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenPortAck> parser = PARSER;
          if (parser == null) {
            synchronized (top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenPortAck.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenPortAck>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:top.meethigher.proxy.tcp.tunnel.proto.OpenPortAck)
    private static final top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenPortAck DEFAULT_INSTANCE;
    static {
      OpenPortAck defaultInstance = new OpenPortAck();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        OpenPortAck.class, defaultInstance);
    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenPortAck getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<OpenPortAck> PARSER;

    public static com.google.protobuf.Parser<OpenPortAck> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface ConnectPortOrBuilder extends
      // @@protoc_insertion_point(interface_extends:top.meethigher.proxy.tcp.tunnel.proto.ConnectPort)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int32 port = 2222;</code>
     * @return The port.
     */
    int getPort();
  }
  /**
   * Protobuf type {@code top.meethigher.proxy.tcp.tunnel.proto.ConnectPort}
   */
  public  static final class ConnectPort extends
      com.google.protobuf.GeneratedMessageLite<
          ConnectPort, ConnectPort.Builder> implements
      // @@protoc_insertion_point(message_implements:top.meethigher.proxy.tcp.tunnel.proto.ConnectPort)
      ConnectPortOrBuilder {
    private ConnectPort() {
    }
    public static final int PORT_FIELD_NUMBER = 2222;
    private int port_;
    /**
     * <code>int32 port = 2222;</code>
     * @return The port.
     */
    @java.lang.Override
    public int getPort() {
      return port_;
    }
    /**
     * <code>int32 port = 2222;</code>
     * @param value The port to set.
     */
    private void setPort(int value) {
      
      port_ = value;
    }
    /**
     * <code>int32 port = 2222;</code>
     */
    private void clearPort() {

      port_ = 0;
    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.ConnectPort parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.ConnectPort parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.ConnectPort parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.ConnectPort parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.ConnectPort parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.ConnectPort parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.ConnectPort parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.ConnectPort parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.ConnectPort parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.ConnectPort parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.ConnectPort parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.ConnectPort parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.ConnectPort prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code top.meethigher.proxy.tcp.tunnel.proto.ConnectPort}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.ConnectPort, Builder> implements
        // @@protoc_insertion_point(builder_implements:top.meethigher.proxy.tcp.tunnel.proto.ConnectPort)
        top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.ConnectPortOrBuilder {
      // Construct using top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.ConnectPort.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int32 port = 2222;</code>
       * @return The port.
       */
      @java.lang.Override
      public int getPort() {
        return instance.getPort();
      }
      /**
       * <code>int32 port = 2222;</code>
       * @param value The port to set.
       * @return This builder for chaining.
       */
      public Builder setPort(int value) {
        copyOnWrite();
        instance.setPort(value);
        return this;
      }
      /**
       * <code>int32 port = 2222;</code>
       * @return This builder for chaining.
       */
      public Builder clearPort() {
        copyOnWrite();
        instance.clearPort();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:top.meethigher.proxy.tcp.tunnel.proto.ConnectPort)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.ConnectPort();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "port_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u08ae\u08ae\u0001\u0000\u0000\u0000\u08ae\u0004";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.ConnectPort> parser = PARSER;
          if (parser == null) {
            synchronized (top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.ConnectPort.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.ConnectPort>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:top.meethigher.proxy.tcp.tunnel.proto.ConnectPort)
    private static final top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.ConnectPort DEFAULT_INSTANCE;
    static {
      ConnectPort defaultInstance = new ConnectPort();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        ConnectPort.class, defaultInstance);
    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.ConnectPort getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ConnectPort> PARSER;

    public static com.google.protobuf.Parser<ConnectPort> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface ConnectPortAckOrBuilder extends
      // @@protoc_insertion_point(interface_extends:top.meethigher.proxy.tcp.tunnel.proto.ConnectPortAck)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    boolean getSuccess();

    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code top.meethigher.proxy.tcp.tunnel.proto.ConnectPortAck}
   */
  public  static final class ConnectPortAck extends
      com.google.protobuf.GeneratedMessageLite<
          ConnectPortAck, ConnectPortAck.Builder> implements
      // @@protoc_insertion_point(message_implements:top.meethigher.proxy.tcp.tunnel.proto.ConnectPortAck)
      ConnectPortAckOrBuilder {
    private ConnectPortAck() {
      message_ = "";
    }
    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_;
    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }
    /**
     * <code>bool success = 1;</code>
     * @param value The success to set.
     */
    private void setSuccess(boolean value) {
      
      success_ = value;
    }
    /**
     * <code>bool success = 1;</code>
     */
    private void clearSuccess() {

      success_ = false;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private java.lang.String message_;
    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      return message_;
    }
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(message_);
    }
    /**
     * <code>string message = 2;</code>
     * @param value The message to set.
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void setMessage(
        java.lang.String value) {
      value.getClass();  // minimal bytecode null check

      message_ = value;
    }
    /**
     * <code>string message = 2;</code>
     */
    private void clearMessage() {

      message_ = getDefaultInstance().getMessage();
    }
    /**
     * <code>string message = 2;</code>
     * @param value The bytes for message to set.
     */
    private void setMessageBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      message_ = value.toStringUtf8();

    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.ConnectPortAck parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.ConnectPortAck parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.ConnectPortAck parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.ConnectPortAck parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.ConnectPortAck parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.ConnectPortAck parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.ConnectPortAck parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.ConnectPortAck parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.ConnectPortAck parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.ConnectPortAck parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.ConnectPortAck parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.ConnectPortAck parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.ConnectPortAck prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code top.meethigher.proxy.tcp.tunnel.proto.ConnectPortAck}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.ConnectPortAck, Builder> implements
        // @@protoc_insertion_point(builder_implements:top.meethigher.proxy.tcp.tunnel.proto.ConnectPortAck)
        top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.ConnectPortAckOrBuilder {
      // Construct using top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.ConnectPortAck.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>bool success = 1;</code>
       * @return The success.
       */
      @java.lang.Override
      public boolean getSuccess() {
        return instance.getSuccess();
      }
      /**
       * <code>bool success = 1;</code>
       * @param value The success to set.
       * @return This builder for chaining.
       */
      public Builder setSuccess(boolean value) {
        copyOnWrite();
        instance.setSuccess(value);
        return this;
      }
      /**
       * <code>bool success = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSuccess() {
        copyOnWrite();
        instance.clearSuccess();
        return this;
      }

      /**
       * <code>string message = 2;</code>
       * @return The message.
       */
      @java.lang.Override
      public java.lang.String getMessage() {
        return instance.getMessage();
      }
      /**
       * <code>string message = 2;</code>
       * @return The bytes for message.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getMessageBytes() {
        return instance.getMessageBytes();
      }
      /**
       * <code>string message = 2;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        copyOnWrite();
        instance.setMessage(value);
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        copyOnWrite();
        instance.clearMessage();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMessageBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:top.meethigher.proxy.tcp.tunnel.proto.ConnectPortAck)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.ConnectPortAck();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "success_",
              "message_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0007\u0002\u0208" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.ConnectPortAck> parser = PARSER;
          if (parser == null) {
            synchronized (top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.ConnectPortAck.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.ConnectPortAck>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:top.meethigher.proxy.tcp.tunnel.proto.ConnectPortAck)
    private static final top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.ConnectPortAck DEFAULT_INSTANCE;
    static {
      ConnectPortAck defaultInstance = new ConnectPortAck();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        ConnectPortAck.class, defaultInstance);
    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.ConnectPortAck getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<ConnectPortAck> PARSER;

    public static com.google.protobuf.Parser<ConnectPortAck> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
