// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: src/main/java/top/meethigher/proxy/tcp/tunnel/proto/origin/tunnelMessage.proto
// Protobuf Java Version: 4.30.2

package top.meethigher.proxy.tcp.tunnel.proto;

public final class TunnelMessage {
  private TunnelMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface OpenDataPortOrBuilder extends
      // @@protoc_insertion_point(interface_extends:top.meethigher.proxy.tcp.tunnel.proto.OpenDataPort)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string secret = 1;</code>
     * @return The secret.
     */
    java.lang.String getSecret();
    /**
     * <code>string secret = 1;</code>
     * @return The bytes for secret.
     */
    com.google.protobuf.ByteString
        getSecretBytes();

    /**
     * <code>int32 dataProxyPort = 2;</code>
     * @return The dataProxyPort.
     */
    int getDataProxyPort();

    /**
     * <code>string dataProxyName = 3;</code>
     * @return The dataProxyName.
     */
    java.lang.String getDataProxyName();
    /**
     * <code>string dataProxyName = 3;</code>
     * @return The bytes for dataProxyName.
     */
    com.google.protobuf.ByteString
        getDataProxyNameBytes();
  }
  /**
   * Protobuf type {@code top.meethigher.proxy.tcp.tunnel.proto.OpenDataPort}
   */
  public  static final class OpenDataPort extends
      com.google.protobuf.GeneratedMessageLite<
          OpenDataPort, OpenDataPort.Builder> implements
      // @@protoc_insertion_point(message_implements:top.meethigher.proxy.tcp.tunnel.proto.OpenDataPort)
      OpenDataPortOrBuilder {
    private OpenDataPort() {
      secret_ = "";
      dataProxyName_ = "";
    }
    public static final int SECRET_FIELD_NUMBER = 1;
    private java.lang.String secret_;
    /**
     * <code>string secret = 1;</code>
     * @return The secret.
     */
    @java.lang.Override
    public java.lang.String getSecret() {
      return secret_;
    }
    /**
     * <code>string secret = 1;</code>
     * @return The bytes for secret.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSecretBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(secret_);
    }
    /**
     * <code>string secret = 1;</code>
     * @param value The secret to set.
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void setSecret(
        java.lang.String value) {
      value.getClass();  // minimal bytecode null check

      secret_ = value;
    }
    /**
     * <code>string secret = 1;</code>
     */
    private void clearSecret() {

      secret_ = getDefaultInstance().getSecret();
    }
    /**
     * <code>string secret = 1;</code>
     * @param value The bytes for secret to set.
     */
    private void setSecretBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      secret_ = value.toStringUtf8();

    }

    public static final int DATAPROXYPORT_FIELD_NUMBER = 2;
    private int dataProxyPort_;
    /**
     * <code>int32 dataProxyPort = 2;</code>
     * @return The dataProxyPort.
     */
    @java.lang.Override
    public int getDataProxyPort() {
      return dataProxyPort_;
    }
    /**
     * <code>int32 dataProxyPort = 2;</code>
     * @param value The dataProxyPort to set.
     */
    private void setDataProxyPort(int value) {
      
      dataProxyPort_ = value;
    }
    /**
     * <code>int32 dataProxyPort = 2;</code>
     */
    private void clearDataProxyPort() {

      dataProxyPort_ = 0;
    }

    public static final int DATAPROXYNAME_FIELD_NUMBER = 3;
    private java.lang.String dataProxyName_;
    /**
     * <code>string dataProxyName = 3;</code>
     * @return The dataProxyName.
     */
    @java.lang.Override
    public java.lang.String getDataProxyName() {
      return dataProxyName_;
    }
    /**
     * <code>string dataProxyName = 3;</code>
     * @return The bytes for dataProxyName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDataProxyNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(dataProxyName_);
    }
    /**
     * <code>string dataProxyName = 3;</code>
     * @param value The dataProxyName to set.
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void setDataProxyName(
        java.lang.String value) {
      value.getClass();  // minimal bytecode null check

      dataProxyName_ = value;
    }
    /**
     * <code>string dataProxyName = 3;</code>
     */
    private void clearDataProxyName() {

      dataProxyName_ = getDefaultInstance().getDataProxyName();
    }
    /**
     * <code>string dataProxyName = 3;</code>
     * @param value The bytes for dataProxyName to set.
     */
    private void setDataProxyNameBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      dataProxyName_ = value.toStringUtf8();

    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataPort parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataPort parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataPort parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataPort parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataPort parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataPort parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataPort parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataPort parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataPort parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataPort parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataPort parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataPort parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataPort prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code top.meethigher.proxy.tcp.tunnel.proto.OpenDataPort}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataPort, Builder> implements
        // @@protoc_insertion_point(builder_implements:top.meethigher.proxy.tcp.tunnel.proto.OpenDataPort)
        top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataPortOrBuilder {
      // Construct using top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataPort.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string secret = 1;</code>
       * @return The secret.
       */
      @java.lang.Override
      public java.lang.String getSecret() {
        return instance.getSecret();
      }
      /**
       * <code>string secret = 1;</code>
       * @return The bytes for secret.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getSecretBytes() {
        return instance.getSecretBytes();
      }
      /**
       * <code>string secret = 1;</code>
       * @param value The secret to set.
       * @return This builder for chaining.
       */
      public Builder setSecret(
          java.lang.String value) {
        copyOnWrite();
        instance.setSecret(value);
        return this;
      }
      /**
       * <code>string secret = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSecret() {
        copyOnWrite();
        instance.clearSecret();
        return this;
      }
      /**
       * <code>string secret = 1;</code>
       * @param value The bytes for secret to set.
       * @return This builder for chaining.
       */
      public Builder setSecretBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSecretBytes(value);
        return this;
      }

      /**
       * <code>int32 dataProxyPort = 2;</code>
       * @return The dataProxyPort.
       */
      @java.lang.Override
      public int getDataProxyPort() {
        return instance.getDataProxyPort();
      }
      /**
       * <code>int32 dataProxyPort = 2;</code>
       * @param value The dataProxyPort to set.
       * @return This builder for chaining.
       */
      public Builder setDataProxyPort(int value) {
        copyOnWrite();
        instance.setDataProxyPort(value);
        return this;
      }
      /**
       * <code>int32 dataProxyPort = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDataProxyPort() {
        copyOnWrite();
        instance.clearDataProxyPort();
        return this;
      }

      /**
       * <code>string dataProxyName = 3;</code>
       * @return The dataProxyName.
       */
      @java.lang.Override
      public java.lang.String getDataProxyName() {
        return instance.getDataProxyName();
      }
      /**
       * <code>string dataProxyName = 3;</code>
       * @return The bytes for dataProxyName.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getDataProxyNameBytes() {
        return instance.getDataProxyNameBytes();
      }
      /**
       * <code>string dataProxyName = 3;</code>
       * @param value The dataProxyName to set.
       * @return This builder for chaining.
       */
      public Builder setDataProxyName(
          java.lang.String value) {
        copyOnWrite();
        instance.setDataProxyName(value);
        return this;
      }
      /**
       * <code>string dataProxyName = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDataProxyName() {
        copyOnWrite();
        instance.clearDataProxyName();
        return this;
      }
      /**
       * <code>string dataProxyName = 3;</code>
       * @param value The bytes for dataProxyName to set.
       * @return This builder for chaining.
       */
      public Builder setDataProxyNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setDataProxyNameBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:top.meethigher.proxy.tcp.tunnel.proto.OpenDataPort)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataPort();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "secret_",
              "dataProxyPort_",
              "dataProxyName_",
            };
            java.lang.String info =
                "\u0000\u0003\u0000\u0000\u0001\u0003\u0003\u0000\u0000\u0000\u0001\u0208\u0002\u0004" +
                "\u0003\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataPort> parser = PARSER;
          if (parser == null) {
            synchronized (top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataPort.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataPort>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:top.meethigher.proxy.tcp.tunnel.proto.OpenDataPort)
    private static final top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataPort DEFAULT_INSTANCE;
    static {
      OpenDataPort defaultInstance = new OpenDataPort();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        OpenDataPort.class, defaultInstance);
    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataPort getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<OpenDataPort> PARSER;

    public static com.google.protobuf.Parser<OpenDataPort> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface OpenDataPortAckOrBuilder extends
      // @@protoc_insertion_point(interface_extends:top.meethigher.proxy.tcp.tunnel.proto.OpenDataPortAck)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    boolean getSuccess();

    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code top.meethigher.proxy.tcp.tunnel.proto.OpenDataPortAck}
   */
  public  static final class OpenDataPortAck extends
      com.google.protobuf.GeneratedMessageLite<
          OpenDataPortAck, OpenDataPortAck.Builder> implements
      // @@protoc_insertion_point(message_implements:top.meethigher.proxy.tcp.tunnel.proto.OpenDataPortAck)
      OpenDataPortAckOrBuilder {
    private OpenDataPortAck() {
      message_ = "";
    }
    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_;
    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }
    /**
     * <code>bool success = 1;</code>
     * @param value The success to set.
     */
    private void setSuccess(boolean value) {
      
      success_ = value;
    }
    /**
     * <code>bool success = 1;</code>
     */
    private void clearSuccess() {

      success_ = false;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private java.lang.String message_;
    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      return message_;
    }
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(message_);
    }
    /**
     * <code>string message = 2;</code>
     * @param value The message to set.
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void setMessage(
        java.lang.String value) {
      value.getClass();  // minimal bytecode null check

      message_ = value;
    }
    /**
     * <code>string message = 2;</code>
     */
    private void clearMessage() {

      message_ = getDefaultInstance().getMessage();
    }
    /**
     * <code>string message = 2;</code>
     * @param value The bytes for message to set.
     */
    private void setMessageBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      message_ = value.toStringUtf8();

    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataPortAck parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataPortAck parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataPortAck parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataPortAck parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataPortAck parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataPortAck parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataPortAck parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataPortAck parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataPortAck parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataPortAck parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataPortAck parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataPortAck parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataPortAck prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code top.meethigher.proxy.tcp.tunnel.proto.OpenDataPortAck}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataPortAck, Builder> implements
        // @@protoc_insertion_point(builder_implements:top.meethigher.proxy.tcp.tunnel.proto.OpenDataPortAck)
        top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataPortAckOrBuilder {
      // Construct using top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataPortAck.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>bool success = 1;</code>
       * @return The success.
       */
      @java.lang.Override
      public boolean getSuccess() {
        return instance.getSuccess();
      }
      /**
       * <code>bool success = 1;</code>
       * @param value The success to set.
       * @return This builder for chaining.
       */
      public Builder setSuccess(boolean value) {
        copyOnWrite();
        instance.setSuccess(value);
        return this;
      }
      /**
       * <code>bool success = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSuccess() {
        copyOnWrite();
        instance.clearSuccess();
        return this;
      }

      /**
       * <code>string message = 2;</code>
       * @return The message.
       */
      @java.lang.Override
      public java.lang.String getMessage() {
        return instance.getMessage();
      }
      /**
       * <code>string message = 2;</code>
       * @return The bytes for message.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getMessageBytes() {
        return instance.getMessageBytes();
      }
      /**
       * <code>string message = 2;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        copyOnWrite();
        instance.setMessage(value);
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        copyOnWrite();
        instance.clearMessage();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMessageBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:top.meethigher.proxy.tcp.tunnel.proto.OpenDataPortAck)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataPortAck();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "success_",
              "message_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0007\u0002\u0208" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataPortAck> parser = PARSER;
          if (parser == null) {
            synchronized (top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataPortAck.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataPortAck>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:top.meethigher.proxy.tcp.tunnel.proto.OpenDataPortAck)
    private static final top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataPortAck DEFAULT_INSTANCE;
    static {
      OpenDataPortAck defaultInstance = new OpenDataPortAck();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        OpenDataPortAck.class, defaultInstance);
    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataPortAck getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<OpenDataPortAck> PARSER;

    public static com.google.protobuf.Parser<OpenDataPortAck> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface HeartbeatOrBuilder extends
      // @@protoc_insertion_point(interface_extends:top.meethigher.proxy.tcp.tunnel.proto.Heartbeat)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int64 timestamp = 1;</code>
     * @return The timestamp.
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code top.meethigher.proxy.tcp.tunnel.proto.Heartbeat}
   */
  public  static final class Heartbeat extends
      com.google.protobuf.GeneratedMessageLite<
          Heartbeat, Heartbeat.Builder> implements
      // @@protoc_insertion_point(message_implements:top.meethigher.proxy.tcp.tunnel.proto.Heartbeat)
      HeartbeatOrBuilder {
    private Heartbeat() {
    }
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timestamp_;
    /**
     * <code>int64 timestamp = 1;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>int64 timestamp = 1;</code>
     * @param value The timestamp to set.
     */
    private void setTimestamp(long value) {
      
      timestamp_ = value;
    }
    /**
     * <code>int64 timestamp = 1;</code>
     */
    private void clearTimestamp() {

      timestamp_ = 0L;
    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Heartbeat parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Heartbeat parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Heartbeat parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Heartbeat parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Heartbeat parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Heartbeat parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Heartbeat parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Heartbeat parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Heartbeat parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Heartbeat parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Heartbeat parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Heartbeat parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Heartbeat prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code top.meethigher.proxy.tcp.tunnel.proto.Heartbeat}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Heartbeat, Builder> implements
        // @@protoc_insertion_point(builder_implements:top.meethigher.proxy.tcp.tunnel.proto.Heartbeat)
        top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.HeartbeatOrBuilder {
      // Construct using top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Heartbeat.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int64 timestamp = 1;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return instance.getTimestamp();
      }
      /**
       * <code>int64 timestamp = 1;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        copyOnWrite();
        instance.setTimestamp(value);
        return this;
      }
      /**
       * <code>int64 timestamp = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        copyOnWrite();
        instance.clearTimestamp();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:top.meethigher.proxy.tcp.tunnel.proto.Heartbeat)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Heartbeat();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "timestamp_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0002";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Heartbeat> parser = PARSER;
          if (parser == null) {
            synchronized (top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Heartbeat.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Heartbeat>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:top.meethigher.proxy.tcp.tunnel.proto.Heartbeat)
    private static final top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Heartbeat DEFAULT_INSTANCE;
    static {
      Heartbeat defaultInstance = new Heartbeat();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Heartbeat.class, defaultInstance);
    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.Heartbeat getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Heartbeat> PARSER;

    public static com.google.protobuf.Parser<Heartbeat> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface HeartbeatAckOrBuilder extends
      // @@protoc_insertion_point(interface_extends:top.meethigher.proxy.tcp.tunnel.proto.HeartbeatAck)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int64 timestamp = 1;</code>
     * @return The timestamp.
     */
    long getTimestamp();
  }
  /**
   * Protobuf type {@code top.meethigher.proxy.tcp.tunnel.proto.HeartbeatAck}
   */
  public  static final class HeartbeatAck extends
      com.google.protobuf.GeneratedMessageLite<
          HeartbeatAck, HeartbeatAck.Builder> implements
      // @@protoc_insertion_point(message_implements:top.meethigher.proxy.tcp.tunnel.proto.HeartbeatAck)
      HeartbeatAckOrBuilder {
    private HeartbeatAck() {
    }
    public static final int TIMESTAMP_FIELD_NUMBER = 1;
    private long timestamp_;
    /**
     * <code>int64 timestamp = 1;</code>
     * @return The timestamp.
     */
    @java.lang.Override
    public long getTimestamp() {
      return timestamp_;
    }
    /**
     * <code>int64 timestamp = 1;</code>
     * @param value The timestamp to set.
     */
    private void setTimestamp(long value) {
      
      timestamp_ = value;
    }
    /**
     * <code>int64 timestamp = 1;</code>
     */
    private void clearTimestamp() {

      timestamp_ = 0L;
    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.HeartbeatAck parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.HeartbeatAck parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.HeartbeatAck parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.HeartbeatAck parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.HeartbeatAck parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.HeartbeatAck parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.HeartbeatAck parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.HeartbeatAck parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.HeartbeatAck parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.HeartbeatAck parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.HeartbeatAck parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.HeartbeatAck parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.HeartbeatAck prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code top.meethigher.proxy.tcp.tunnel.proto.HeartbeatAck}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.HeartbeatAck, Builder> implements
        // @@protoc_insertion_point(builder_implements:top.meethigher.proxy.tcp.tunnel.proto.HeartbeatAck)
        top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.HeartbeatAckOrBuilder {
      // Construct using top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.HeartbeatAck.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int64 timestamp = 1;</code>
       * @return The timestamp.
       */
      @java.lang.Override
      public long getTimestamp() {
        return instance.getTimestamp();
      }
      /**
       * <code>int64 timestamp = 1;</code>
       * @param value The timestamp to set.
       * @return This builder for chaining.
       */
      public Builder setTimestamp(long value) {
        copyOnWrite();
        instance.setTimestamp(value);
        return this;
      }
      /**
       * <code>int64 timestamp = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTimestamp() {
        copyOnWrite();
        instance.clearTimestamp();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:top.meethigher.proxy.tcp.tunnel.proto.HeartbeatAck)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.HeartbeatAck();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "timestamp_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0002";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.HeartbeatAck> parser = PARSER;
          if (parser == null) {
            synchronized (top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.HeartbeatAck.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.HeartbeatAck>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:top.meethigher.proxy.tcp.tunnel.proto.HeartbeatAck)
    private static final top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.HeartbeatAck DEFAULT_INSTANCE;
    static {
      HeartbeatAck defaultInstance = new HeartbeatAck();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        HeartbeatAck.class, defaultInstance);
    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.HeartbeatAck getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<HeartbeatAck> PARSER;

    public static com.google.protobuf.Parser<HeartbeatAck> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface OpenDataConnOrBuilder extends
      // @@protoc_insertion_point(interface_extends:top.meethigher.proxy.tcp.tunnel.proto.OpenDataConn)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int32 dataProxyPort = 1;</code>
     * @return The dataProxyPort.
     */
    int getDataProxyPort();
  }
  /**
   * Protobuf type {@code top.meethigher.proxy.tcp.tunnel.proto.OpenDataConn}
   */
  public  static final class OpenDataConn extends
      com.google.protobuf.GeneratedMessageLite<
          OpenDataConn, OpenDataConn.Builder> implements
      // @@protoc_insertion_point(message_implements:top.meethigher.proxy.tcp.tunnel.proto.OpenDataConn)
      OpenDataConnOrBuilder {
    private OpenDataConn() {
    }
    public static final int DATAPROXYPORT_FIELD_NUMBER = 1;
    private int dataProxyPort_;
    /**
     * <code>int32 dataProxyPort = 1;</code>
     * @return The dataProxyPort.
     */
    @java.lang.Override
    public int getDataProxyPort() {
      return dataProxyPort_;
    }
    /**
     * <code>int32 dataProxyPort = 1;</code>
     * @param value The dataProxyPort to set.
     */
    private void setDataProxyPort(int value) {
      
      dataProxyPort_ = value;
    }
    /**
     * <code>int32 dataProxyPort = 1;</code>
     */
    private void clearDataProxyPort() {

      dataProxyPort_ = 0;
    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataConn parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataConn parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataConn parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataConn parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataConn parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataConn parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataConn parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataConn parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataConn parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataConn parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataConn parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataConn parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataConn prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code top.meethigher.proxy.tcp.tunnel.proto.OpenDataConn}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataConn, Builder> implements
        // @@protoc_insertion_point(builder_implements:top.meethigher.proxy.tcp.tunnel.proto.OpenDataConn)
        top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataConnOrBuilder {
      // Construct using top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataConn.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int32 dataProxyPort = 1;</code>
       * @return The dataProxyPort.
       */
      @java.lang.Override
      public int getDataProxyPort() {
        return instance.getDataProxyPort();
      }
      /**
       * <code>int32 dataProxyPort = 1;</code>
       * @param value The dataProxyPort to set.
       * @return This builder for chaining.
       */
      public Builder setDataProxyPort(int value) {
        copyOnWrite();
        instance.setDataProxyPort(value);
        return this;
      }
      /**
       * <code>int32 dataProxyPort = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearDataProxyPort() {
        copyOnWrite();
        instance.clearDataProxyPort();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:top.meethigher.proxy.tcp.tunnel.proto.OpenDataConn)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataConn();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "dataProxyPort_",
            };
            java.lang.String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\u0004";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataConn> parser = PARSER;
          if (parser == null) {
            synchronized (top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataConn.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataConn>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:top.meethigher.proxy.tcp.tunnel.proto.OpenDataConn)
    private static final top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataConn DEFAULT_INSTANCE;
    static {
      OpenDataConn defaultInstance = new OpenDataConn();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        OpenDataConn.class, defaultInstance);
    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataConn getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<OpenDataConn> PARSER;

    public static com.google.protobuf.Parser<OpenDataConn> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface OpenDataConnAckOrBuilder extends
      // @@protoc_insertion_point(interface_extends:top.meethigher.proxy.tcp.tunnel.proto.OpenDataConnAck)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    boolean getSuccess();

    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code top.meethigher.proxy.tcp.tunnel.proto.OpenDataConnAck}
   */
  public  static final class OpenDataConnAck extends
      com.google.protobuf.GeneratedMessageLite<
          OpenDataConnAck, OpenDataConnAck.Builder> implements
      // @@protoc_insertion_point(message_implements:top.meethigher.proxy.tcp.tunnel.proto.OpenDataConnAck)
      OpenDataConnAckOrBuilder {
    private OpenDataConnAck() {
      message_ = "";
    }
    public static final int SUCCESS_FIELD_NUMBER = 1;
    private boolean success_;
    /**
     * <code>bool success = 1;</code>
     * @return The success.
     */
    @java.lang.Override
    public boolean getSuccess() {
      return success_;
    }
    /**
     * <code>bool success = 1;</code>
     * @param value The success to set.
     */
    private void setSuccess(boolean value) {
      
      success_ = value;
    }
    /**
     * <code>bool success = 1;</code>
     */
    private void clearSuccess() {

      success_ = false;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private java.lang.String message_;
    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      return message_;
    }
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(message_);
    }
    /**
     * <code>string message = 2;</code>
     * @param value The message to set.
     */
    @java.lang.SuppressWarnings("ReturnValueIgnored")
    private void setMessage(
        java.lang.String value) {
      value.getClass();  // minimal bytecode null check

      message_ = value;
    }
    /**
     * <code>string message = 2;</code>
     */
    private void clearMessage() {

      message_ = getDefaultInstance().getMessage();
    }
    /**
     * <code>string message = 2;</code>
     * @param value The bytes for message to set.
     */
    private void setMessageBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      message_ = value.toStringUtf8();

    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataConnAck parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataConnAck parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataConnAck parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataConnAck parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataConnAck parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataConnAck parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataConnAck parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataConnAck parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataConnAck parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataConnAck parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataConnAck parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataConnAck parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataConnAck prototype) {
      return DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code top.meethigher.proxy.tcp.tunnel.proto.OpenDataConnAck}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataConnAck, Builder> implements
        // @@protoc_insertion_point(builder_implements:top.meethigher.proxy.tcp.tunnel.proto.OpenDataConnAck)
        top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataConnAckOrBuilder {
      // Construct using top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataConnAck.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>bool success = 1;</code>
       * @return The success.
       */
      @java.lang.Override
      public boolean getSuccess() {
        return instance.getSuccess();
      }
      /**
       * <code>bool success = 1;</code>
       * @param value The success to set.
       * @return This builder for chaining.
       */
      public Builder setSuccess(boolean value) {
        copyOnWrite();
        instance.setSuccess(value);
        return this;
      }
      /**
       * <code>bool success = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSuccess() {
        copyOnWrite();
        instance.clearSuccess();
        return this;
      }

      /**
       * <code>string message = 2;</code>
       * @return The message.
       */
      @java.lang.Override
      public java.lang.String getMessage() {
        return instance.getMessage();
      }
      /**
       * <code>string message = 2;</code>
       * @return The bytes for message.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getMessageBytes() {
        return instance.getMessageBytes();
      }
      /**
       * <code>string message = 2;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        copyOnWrite();
        instance.setMessage(value);
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        copyOnWrite();
        instance.clearMessage();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMessageBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:top.meethigher.proxy.tcp.tunnel.proto.OpenDataConnAck)
    }
    @java.lang.Override
    @java.lang.SuppressWarnings({"ThrowNull"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0, java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataConnAck();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            java.lang.Object[] objects = new java.lang.Object[] {
              "success_",
              "message_",
            };
            java.lang.String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0007\u0002\u0208" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataConnAck> parser = PARSER;
          if (parser == null) {
            synchronized (top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataConnAck.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataConnAck>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
        }
        case GET_MEMOIZED_IS_INITIALIZED: {
          return (byte) 1;
        }
        // SET_MEMOIZED_IS_INITIALIZED is never called for this message.
        // So it can do anything. Combine with default case for smaller codegen.
        case SET_MEMOIZED_IS_INITIALIZED:
      }
      // Should never happen. Generates tight code to throw an exception.
      throw null;
    }


    // @@protoc_insertion_point(class_scope:top.meethigher.proxy.tcp.tunnel.proto.OpenDataConnAck)
    private static final top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataConnAck DEFAULT_INSTANCE;
    static {
      OpenDataConnAck defaultInstance = new OpenDataConnAck();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        OpenDataConnAck.class, defaultInstance);
    }

    public static top.meethigher.proxy.tcp.tunnel.proto.TunnelMessage.OpenDataConnAck getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<OpenDataConnAck> PARSER;

    public static com.google.protobuf.Parser<OpenDataConnAck> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
